project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Machine Learning Fundamentals"
            file: content/01_journal/01_machine_learning_fundamentals.qmd
          - text: "02 Supervised ML Regression"
            file: content/01_journal/02_supervised_ml_regression.qmd
          - text: "03 Automated Machine Learning 1"
            file: content/01_journal/03_automated_machine_learning_1.qmd
          - text: "04 Automated Machine Learning 2"
            file: content/01_journal/04_automated_machine_learning_2.qmd
          - text: "05 Performance Measures"
            file: content/01_journal/05_performance_measures.qmd
          - text: "06 Explaining Black-Box Models with LIME"
            file: content/01_journal/06_explaining_black_box_models_with_lime.qmd
      - text: "Class notes"
        file: content/02_notes/07_class_notes.qmd
      - text: "Links"
        file: content/03_other/08_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto